### ISSUE TITLE
Module Mechanism

### ISSUE THREAD

**Issue by tanbowensg** [webzard-io/sunmao-ui#102]
# Use cases
* You build a complicated form by meta-ui and want to reuse it in multiple meta-ui application.
* You build a fancy listItemView and want to use it in list.

# module vs component
Module is made up of meta-ui component. Component is created in react.

# Features of module
Basicly, module can be used like a component. Module can receive properties and expose state & events.

# Tasks
- [x] define spec and schema
- [x] render module as item of table td and listItem
- [x] render module individually
- [x] create module in editor
- [x] edit module in editor
